adding major changes

diff --git a/.github/workflows/sonar_scan.yml b/.github/workflows/sonar_scan.yml
--- a/.github/workflows/sonar_scan.yml
+++ b/.github/workflows/sonar_scan.yml
@@ -1,40 +1,33 @@
-# Goal - to check whether the application code has security threats/issues using GitHub CodeQL
+# Goal - to check whether the application code coverage doesn't have security threats/issues
 
-name: Security Scan (CodeQL)
+name: Sonar Qube Scan
 
 on:
     workflow_call:
 
 jobs:
-    analyze:
-        name: CodeQL Analyze
+    sonar-scanner:
         runs-on: ubuntu-latest
-        permissions:
-          # Required to write security alerts back to the repository's Security tab
-          security-events: write
-          actions: read
-          contents: read
-
         steps:
             - name: Code Checkout
               uses: actions/checkout@v4
               with:
                 fetch-depth: 0
-
-            # Step 1: Initialize the CodeQL tools and define target languages
-            - name: Initialize CodeQL
-              uses: github/codeql-action/init@v3
+             
+            -  name: Verify Secret Presence
+               run: |
+                if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
+                  echo "❌ ERROR: SONAR_TOKEN is completely empty inside this workflow!"
+                  exit 1
+                else
+                  echo "✅ SONAR_TOKEN is present."
+                fi
+            - name: SonarQube Scan
+              uses: SonarSource/sonarqube-scan-action@v7
               with:
-                # Options include: javascript-typescript, python, go, java-kotlin, csharp, cpp, ruby
-                languages: javascript-typescript 
-
-            # Step 2: Automatically attempt to build compiled languages (if applicable)
-            # For JavaScript/Python/Ruby, this step can safely remain but does nothing.
-            - name: Autobuild
-              uses: github/codeql-action/autobuild@v3
-
-            # Step 3: Run the deep security analysis
-            - name: Perform CodeQL Analysis
-              uses: github/codeql-action/analyze@v3
-              with:
-                category: "/language:javascript-typescript"
+                args: >
+                  -Dsonar.organization=onkarghuare08
+                  -Dsonar.projectKey=devboard
+              env:
+                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
